// categories.js
export const categories = {
    "Glass Candles": {
      options: ["Big Glass", "Medium Glass"],
      subOptions: {
        "Big Glass": [
          "Vanilla",
          "Strawberry Shortcake",
          "Berries",
          "Chocolate",
          "Coffee",
          "Sandalwood",
          "Mint",
          "Lemon",
          "Jasmine",
          "Cotton Candy",
          "Lemon Grass",
          "Rose",
          "Green Apple",
          "Bubble Gum",
          "Creamy Peach",
          "Mix Fruit",
          "Lavender",
        ],
        "Medium Glass": [
          "Berry Bonanza",
          "Flower Valley",
          "Purple Rain",
          "Green Apple",
          "Bubble Gum",
          "Royal Rose",
          "Eucalyptus",
          "Spa Retreat",
          "Peach Mango",
          "Cocoa Butter",
        ],
      },
    },
    "Mold Candles": [
      "Daisy",
      "Owl",
      "Cactus",
      "Cake Small",
      "Cupcake",
      "Cheese Stack",
      "Peony",
      "Body",
      "Small Bubble",
      "Rose Love",
      "Couple",
      "Cube Love",
      "Big Bubble",
      "Cake",
      "Hug",
      "Floral Pillar",
      "Christmas Pillar & Christmas Ball",
    ],
  };